language: node_js
sudo: require
services:
  - docker

before_install:
  - docker build -t tsungtingdu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tsungtingdu/react-test npm test -- --coverage

after_sucess:
  - docker build -t tsungtingdu/multi-client ./client
  - docker build -t tsungtingdu/multi-server ./server
  - docker build -t tsungtingdu/multi-worker ./worker
  - docker build -t tsungtingdu/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push tsungtingdu/multi-client
  - docker push tsungtingdu/multi-server 
  - docker push tsungtingdu/multi-worker
  - docker push tsungtingdu/multi-nginx 

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"  
  app: "multiple-services" 
  env: "MultipleServices-env"
  bucket_name: "elasticbeanstalk-us-east-2-516245968608"
  bucket_path: "docker-multiple-services"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY